export const ITEM = {
  LOAD_TOP_STORIES_SUCCESS: 'LOAD_TOP_STORIES_SUCCESS',
  LOAD_ITEM_SUCCESS: 'LOAD_ITEM_SUCCESS',
  LOAD_ITEM_ERROR: 'LOAD_ITEM_ERROR'
};

export const COMMON = {
  LOAD_START: 'LOAD_START',
  LOAD_ERROR: 'LOAD_ERROR'
};
